site_name: IdeaSphere docs
site_url: https://docs.ideasphere.org
theme:
  name: material
  language: zh
  logo: /assets/logo.png
  favicon: /assets/favicon.ico

extra:
  homepage: https://ideasphere.org